fixed dependency change
hms-networks/discourse-survey pull request #1
Opened 2019-11-05 16:24 UTC by oliver-walker-hms

same as other plugin fix, build_email function got moved. fixed dependency change.

2019-11-05 16:45 UTC, alexjhawk approved these changes

2019-11-05 18:23 UTC, TomKimsey requested changes
Same thing for this one. The commit body should explain why the change was made. With these forum plugins its especially important to explain why a change is made so that if someone not involved with the project looks at the commit they can learn why the change was made.

2019-11-06 18:27 UTC, oliver-walker-hms commented
this is ready for review

2019-11-06 18:41 UTC, TomKimsey approved these changes

2019-11-06 18:49 UTC, merged